language: php

sudo: false

php:
  - "5.6"

before_script:
  - nvm install 4.2
  - npm install

script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;


after_success:
  # Run npm build task.
  - run npm build
